// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtpjdwxfrqmguggkwlmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0cGpkd3hmcnFtZ3VnZ2t3bG13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA0Mjc2NzQsImV4cCI6MjA0NjAwMzY3NH0.w97LbeuSmOPYilciB6Kt3onM5BItoJTGdeYT9r3HO5E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);